label: "WMT14 Deep Decoder Subwords"
description: "Baseline WMT14 model with conditional decoder + joint subwords"

cell_size: 1000
attn_size: 1000
embedding_size: 620
cell_type: GRU

data_dir: data/WMT14_en_de
max_len: 60
model_dir: models/WMT14_en_de/subwords
max_train_size: 1000000
vocab_prefix: vocab.concat

steps_per_checkpoint: 5000
steps_per_eval: 5000
keep_best: 1
max_to_keep: 1

optimizer: adam
learning_rate: 0.0002
batch_size: 80
batch_mode: standard
read_ahead: 20
max_gradient_norm: 1.0
max_epochs: 10
learning_rate_decay_factor: 0.5
decay_every_n_epoch: 1

attention_type: global
final_state: last_both

encoders:
  - name: joint
    ext: 30k.en
    position_bias: True

decoders:
  - name: joint
    ext: 30k.de
    pred_deep_layer: True

embedding_weight_scale: 0.1
weight_scale: null
orthogonal_init: True

use_dropout: True
pervasive_dropout: True
rnn_input_dropout: 0.2
attn_dropout: 0.2
embedding_dropout: 0.2
initial_state_dropout: 0.2
