label: 'BTEC baseline'
description: "multi-speaker baseline on BTEC, same configuration as Berard et al. 2016"

data_dir: data/BTEC
model_dir: models/BTEC/AST/baseline
train_prefix: train.concat.shuf  # Michel, Philippe, Loic, Marion, Helene, Fabienne
max_train_size: 20000

optimizer: adam
learning_rate: 0.001
batch_size: 64
batch_mode: standard
read_ahead: 10
max_gradient_norm: 5.0
weight_scale: null

steps_per_checkpoint: 1000
steps_per_eval: 1000
max_steps: 30000

cell_size: 256
attn_size: 256
cell_type: LSTM

encoders:
  - name: feats41
    embedding_size: 41
    layers: 3
    time_pooling: [2, 2]
    pooling_avg: True
    binary: True
    attn_filters: 1
    attn_filter_length: 25
    max_len: 600
    input_layers: [256, 256]
    bidir_projection: True
    final_state: concat_last
    train_initial_states: False
    bidir: True

decoders:
  - name: en
    layers: 2
    embedding_size: 256
    max_len: 25
    pred_maxout_layer: False
    rnn_feed_attn: False
    use_previous_word: False
    pred_use_lstm_state: False
    pred_embed_proj: False
    attn_prev_word: False
    update_first: True

use_dropout: True
rnn_input_dropout: 0.5
initial_state_dropout: 0.5
input_layer_dropout: 0.5
reverse_input: True
use_lstm_full_state: True
