label: 'LibriSpeech ASR'
description: "Character-Level Automatic Speech Recognition on LibriSpeech"

data_dir: data/ICASSP/Books
model_dir: models/ICASSP/Books/ASR
max_train_size: 20000

batch_size: 32
weight_scale: null

steps_per_checkpoint: 1000
steps_per_eval: 1000
max_steps: 500000
score_function: corpus_scores_wer

cell_size: 256
attn_size: 256
cell_type: LSTM

encoders:
  - name: feats41
    embedding_size: 41
    layers: 3
    cell_size: 256
    conv_filters: [16, 16]
    conv_size: [3, 3]
    conv_strides: [2, 2]
    conv_activation: null
    binary: True
    max_len: 1400
    input_layers: [256, 128]
    input_layer_activation: tanh
    bidir_projection: True
    final_state: average
    train_initial_states: False

decoders:
  - name: char.en
    conditional_rnn: True
    pred_deep_layer: True
    character_level: True
    use_previous_word: True
    deep_layer_size: 256
    embedding_size: 128
    max_len: 300

use_dropout: True
pervasive_dropout: True
attn_dropout: 0.2
rnn_input_dropout: 0.2
initial_state_dropout: 0.2
input_layer_dropout: 0.2
