label: 'BTEC MT'

data_dir: data/ICASSP/BTEC
model_dir: models/ICASSP/BTEC/MT

batch_size: 64
weight_scale: null

steps_per_checkpoint: 2000
steps_per_eval: 2000
max_steps: 100000
score_function: corpus_scores_bleu

cell_size: 256
attn_size: 256
cell_type: LSTM

encoders:
  - name: fr
    embedding_size: 128
    max_len: 25
    bidir_projection: True
    train_initial_states: False
    final_state: average
    embedding_dropout: 0.2

decoders:
  - name: char.en
    layers: 1
    conditional_rnn: True
    character_level: True
    pred_maxout_layer: False
    pred_deep_layer: False
    pred_deep_layer_size: 64
    pred_embed_proj: False
    use_previous_word: False
    embedding_size: 64
    max_len: 120
    word_dropout: 0.2

use_dropout: True
pervasive_dropout: True
attn_dropout: 0.2
rnn_input_dropout: 0.2
initial_state_dropout: 0.2
rnn_output_dropout: 0.2
